/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import java.awt.Button;
import java.awt.Label;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Huseyn
 */
public class GuiIsci extends javax.swing.JFrame {

    /**
     * Creates new form Isci
     */
    public GuiIsci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oneriGonder = new java.awt.Button();
        isim_degisken = new java.awt.Label();
        maas_degisken = new java.awt.Label();
        soyisim_degisken = new java.awt.Label();
        tc_degisken = new java.awt.Label();
        isim = new java.awt.Label();
        soyisim = new java.awt.Label();
        tc = new java.awt.Label();
        maas = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logomini.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 130));

        oneriGonder.setActionCommand("oneri");
        oneriGonder.setBackground(new java.awt.Color(0, 0, 0));
        oneriGonder.setForeground(new java.awt.Color(240, 240, 240));
        oneriGonder.setLabel("ÖNERI GÖNDER");
        oneriGonder.setName("ÖNERİ GÖNDER"); // NOI18N
        oneriGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneriGonderActionPerformed(evt);
            }
        });
        jPanel1.add(oneriGonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 170, 40));

        isim_degisken.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        isim_degisken.setForeground(new java.awt.Color(240, 240, 240));
        isim_degisken.setText(isim_degisken.getText());
        jPanel1.add(isim_degisken, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 290, 30));
        isim_degisken.getAccessibleContext().setAccessibleName("Isim_degisken");

        maas_degisken.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        maas_degisken.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(maas_degisken, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 280, -1));
        maas_degisken.getAccessibleContext().setAccessibleName("maas_degisken");

        soyisim_degisken.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        soyisim_degisken.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(soyisim_degisken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, -1));
        soyisim_degisken.getAccessibleContext().setAccessibleName("soyIsim_degisken");

        tc_degisken.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tc_degisken.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(tc_degisken, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, -1));
        tc_degisken.getAccessibleContext().setAccessibleName("tc_degisken");

        isim.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        isim.setForeground(new java.awt.Color(240, 240, 240));
        isim.setText("Isim:");
        jPanel1.add(isim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, 30));

        soyisim.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        soyisim.setForeground(new java.awt.Color(240, 240, 240));
        soyisim.setText("Soy Isim:");
        jPanel1.add(soyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));

        tc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tc.setForeground(new java.awt.Color(240, 240, 240));
        tc.setText("TC:");
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        maas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        maas.setForeground(new java.awt.Color(240, 240, 240));
        maas.setText("Maas:");
        jPanel1.add(maas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneriGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneriGonderActionPerformed
        // TODO add your handling code here:
        GuiOneriGonder gog= new GuiOneriGonder();
        this.setVisible(false);
        gog.setVisible(true);
    }//GEN-LAST:event_oneriGonderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiIsci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiIsci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiIsci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiIsci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiIsci gi=new GuiIsci();
                gi.setVisible(true);
            }
        });
    }

    public Label getIsim() {
        return isim;
    }

    public void setIsim(Label isim) {
        this.isim = isim;
    }

    public Label getIsim_degisken() {
        return isim_degisken;
    }

    public void setIsim_degisken(Label isim_degisken) {
        this.isim_degisken = isim_degisken;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public Label getMaas() {
        return maas;
    }

    public void setMaas(Label maas) {
        this.maas = maas;
    }

    public Label getMaas_degisken() {
        return maas_degisken;
    }

    public void setMaas_degisken(Label maas_degisken) {
        this.maas_degisken = maas_degisken;
    }

    public Button getOneriGonder() {
        return oneriGonder;
    }

    public void setOneriGonder(Button oneriGonder) {
        this.oneriGonder = oneriGonder;
    }

    public Label getSoyisim() {
        return soyisim;
    }

    public void setSoyisim(Label soyisim) {
        this.soyisim = soyisim;
    }

    public Label getSoyisim_degisken() {
        return soyisim_degisken;
    }

    public void setSoyisim_degisken(Label soyisim_degisken) {
        this.soyisim_degisken = soyisim_degisken;
    }

    public Label getTc() {
        return tc;
    }

    public void setTc(Label tc) {
        this.tc = tc;
    }

    public Label getTc_degisken() {
        return tc_degisken;
    }

    public void setTc_degisken(Label tc_degisken) {
        this.tc_degisken = tc_degisken;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label isim;
    private java.awt.Label isim_degisken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label maas;
    private java.awt.Label maas_degisken;
    private java.awt.Button oneriGonder;
    private java.awt.Label soyisim;
    private java.awt.Label soyisim_degisken;
    private java.awt.Label tc;
    private java.awt.Label tc_degisken;
    // End of variables declaration//GEN-END:variables
}
