/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Huseyn
 */
public class GuiMuzeYoneticisi extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form GMuzeYoneticisi
     */
    public GuiMuzeYoneticisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        personelSil = new java.awt.Button();
        personelListesi = new java.awt.Button();
        oneriler = new java.awt.Button();
        biletFiyatiDegistir = new java.awt.Button();
        personelEkle1 = new java.awt.Button();
        kasa = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logomini.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 130, 130));

        personelSil.setActionCommand("personelSil");
        personelSil.setBackground(new java.awt.Color(0, 0, 0));
        personelSil.setForeground(new java.awt.Color(240, 240, 240));
        personelSil.setLabel("PERSONEL SİL");
        personelSil.setName("PERSONEL SİL"); // NOI18N
        personelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelSilActionPerformed(evt);
            }
        });
        jPanel1.add(personelSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 40));
        personelSil.getAccessibleContext().setAccessibleName("personelSil");

        personelListesi.setActionCommand("musteri");
        personelListesi.setBackground(new java.awt.Color(0, 0, 0));
        personelListesi.setForeground(new java.awt.Color(240, 240, 240));
        personelListesi.setLabel("PERSONEL LISTESI");
        personelListesi.setName("personelListesi"); // NOI18N
        personelListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelListesiActionPerformed(evt);
            }
        });
        jPanel1.add(personelListesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 170, 40));

        oneriler.setActionCommand("oneriler");
        oneriler.setBackground(new java.awt.Color(0, 0, 0));
        oneriler.setForeground(new java.awt.Color(240, 240, 240));
        oneriler.setLabel("ÖNERILER");
        oneriler.setName("oneriler"); // NOI18N
        oneriler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onerilerActionPerformed(evt);
            }
        });
        jPanel1.add(oneriler, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 170, 40));
        oneriler.getAccessibleContext().setAccessibleName("oneriler");

        biletFiyatiDegistir.setActionCommand("fiyatDegistir");
        biletFiyatiDegistir.setBackground(new java.awt.Color(0, 0, 0));
        biletFiyatiDegistir.setForeground(new java.awt.Color(240, 240, 240));
        biletFiyatiDegistir.setLabel("BILET FIYATI DEGISTIR");
        biletFiyatiDegistir.setName("BILET FIYATI DEGISTIR"); // NOI18N
        biletFiyatiDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biletFiyatiDegistirActionPerformed(evt);
            }
        });
        jPanel1.add(biletFiyatiDegistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 170, 40));

        personelEkle1.setActionCommand("personelEkle");
        personelEkle1.setBackground(new java.awt.Color(0, 0, 0));
        personelEkle1.setForeground(new java.awt.Color(240, 240, 240));
        personelEkle1.setLabel("PERSONEL EKLE");
        personelEkle1.setName("PERSONEL EKLE"); // NOI18N
        personelEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelEkle1ActionPerformed(evt);
            }
        });
        jPanel1.add(personelEkle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, 40));

        kasa.setActionCommand("musteri");
        kasa.setBackground(new java.awt.Color(0, 0, 0));
        kasa.setForeground(new java.awt.Color(240, 240, 240));
        kasa.setLabel("KASA");
        kasa.setName("musteri"); // NOI18N
        kasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasaActionPerformed(evt);
            }
        });
        jPanel1.add(kasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personelEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelEkle1ActionPerformed
        GuiPersonelEkle gpe=new GuiPersonelEkle();
        this.setVisible(false);
        gpe.setVisible(true);
    }//GEN-LAST:event_personelEkle1ActionPerformed

    private void personelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelSilActionPerformed
        GuiPersonelSil gps=new GuiPersonelSil();
        this.setVisible(false);
        gps.setVisible(true);
    }//GEN-LAST:event_personelSilActionPerformed

    private void personelListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelListesiActionPerformed

        try {
            GuiPersonel gp=new GuiPersonel();
            gp.setPersoneller(ConnectionDB.personellerTanimla());
            gp.createPersonelTable();
            this.setVisible(false);
            gp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_personelListesiActionPerformed

    private void onerilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onerilerActionPerformed
        try {
            GuiOneri go=new GuiOneri();
            go.setOneriler(ConnectionDB.onerilerTanimla());
            go.createOneriTable();
            this.setVisible(false);
            go.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onerilerActionPerformed

    private void biletFiyatiDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biletFiyatiDegistirActionPerformed
        GuiFiyatDegistir gfd=new GuiFiyatDegistir();
        this.setVisible(false);
        gfd.setVisible(true);
    }//GEN-LAST:event_biletFiyatiDegistirActionPerformed

    private void kasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasaActionPerformed
        // TODO add your handling code here:
        try {
            GuiKasa gk=new GuiKasa();
            this.setVisible(false);
            gk.setKasa(ConnectionDB.kasaTanimla());
            gk.createKasaTable();
            gk.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMuzeYoneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMuzeYoneticisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button biletFiyatiDegistir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button kasa;
    private java.awt.Button oneriler;
    private java.awt.Button personelEkle1;
    private java.awt.Button personelListesi;
    private java.awt.Button personelSil;
    // End of variables declaration//GEN-END:variables
}
