/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Huseyn
 */
public class GuiOneriGonder extends javax.swing.JFrame {

    private String oneri;
    /**
     * Creates new form Oneri
     */
    public GuiOneriGonder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oneriTextArea = new javax.swing.JTextArea();
        anamenu = new java.awt.Button();
        gonder = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ÖNERİ GÖNDER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        oneriTextArea.setColumns(20);
        oneriTextArea.setRows(5);
        jScrollPane1.setViewportView(oneriTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 160));

        anamenu.setActionCommand("anamenu");
        anamenu.setBackground(new java.awt.Color(0, 0, 0));
        anamenu.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        anamenu.setForeground(new java.awt.Color(255, 51, 51));
        anamenu.setLabel("Ana Menüye dön");
        anamenu.setName("anamenu"); // NOI18N
        anamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenuActionPerformed(evt);
            }
        });
        jPanel1.add(anamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));
        anamenu.getAccessibleContext().setAccessibleName("anamenu");
        anamenu.getAccessibleContext().setAccessibleDescription("");

        gonder.setActionCommand("gonder");
        gonder.setBackground(new java.awt.Color(0, 0, 0));
        gonder.setForeground(new java.awt.Color(240, 240, 240));
        gonder.setLabel("GONDER");
        gonder.setName("GÖNDER"); // NOI18N
        gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderActionPerformed(evt);
            }
        });
        jPanel1.add(gonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, 40));
        gonder.getAccessibleContext().setAccessibleName("gonder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenuActionPerformed
        // TODO add your handling code here:
        if(Insan.getTip().equals("1"))
        {
            GuiMusteri gm=new GuiMusteri();
            this.setVisible(false);
            gm.setVisible(true);
        }
        if(Insan.getTip().equals("2"))
        {
            try {
                ConnectionDB.isciBilgileri();
                GuiIsci gi=new GuiIsci();
                gi.getSoyisim_degisken().setText(Insan.getSoyisim());
                gi.getIsim_degisken().setText(Insan.getIsim());
                gi.getTc_degisken().setText(Insan.getTCnum());
                gi.getMaas_degisken().setText(Insan.getMaas());
                this.setVisible(false);
                gi.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(GuiOneriGonder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(Insan.getTip().equals("3"))
        {
            GuiMuzeYoneticisi gmy=new GuiMuzeYoneticisi();
            this.setVisible(false);
            gmy.setVisible(true);
        }
    }//GEN-LAST:event_anamenuActionPerformed

    private void gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderActionPerformed
        oneri=oneriTextArea.getText();
        try {
            ConnectionDB.oneriEkle(oneri);
            JOptionPane.showMessageDialog(null, "Öneriniz müze yöneticisine gönderildi.");
            oneriTextArea.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(GuiOneriGonder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gonderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiOneriGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiOneriGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiOneriGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiOneriGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiOneriGonder().setVisible(true);
            }
        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button anamenu;
    private java.awt.Button gonder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea oneriTextArea;
    // End of variables declaration//GEN-END:variables
}
