/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Huseyn
 */
public class GuiPersonelEkle extends javax.swing.JFrame {
    private String isimT,soyisimT,tcT,sifreT,maasT;
    /**
     * Creates new form GPersonel
     */
    public GuiPersonelEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ekle = new java.awt.Button();
        anamenu = new java.awt.Button();
        sifre = new java.awt.Label();
        maasTextField = new javax.swing.JTextField();
        isim = new java.awt.Label();
        isimTextField1 = new javax.swing.JTextField();
        soyisim = new java.awt.Label();
        soyIsimTextField2 = new javax.swing.JTextField();
        tc = new java.awt.Label();
        tcTextField1 = new javax.swing.JTextField();
        sifreTextField = new javax.swing.JTextField();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ekle.setActionCommand("ekle");
        ekle.setBackground(new java.awt.Color(0, 0, 0));
        ekle.setForeground(new java.awt.Color(240, 240, 240));
        ekle.setLabel("EKLE");
        ekle.setName("EKLE"); // NOI18N
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });
        jPanel1.add(ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 220, 40));

        anamenu.setActionCommand("anamenu");
        anamenu.setBackground(new java.awt.Color(0, 0, 0));
        anamenu.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        anamenu.setForeground(new java.awt.Color(255, 51, 51));
        anamenu.setLabel("Ana Menüye dön");
        anamenu.setName("anamenu"); // NOI18N
        anamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenuActionPerformed(evt);
            }
        });
        jPanel1.add(anamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));

        sifre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        sifre.setForeground(new java.awt.Color(240, 240, 240));
        sifre.setText("Sifre");
        jPanel1.add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 60, 30));
        sifre.getAccessibleContext().setAccessibleName("sifre");

        maasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maasTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(maasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, 30));

        isim.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        isim.setForeground(new java.awt.Color(240, 240, 240));
        isim.setText("Isim");
        jPanel1.add(isim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, 30));

        isimTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(isimTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, 30));

        soyisim.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        soyisim.setForeground(new java.awt.Color(240, 240, 240));
        soyisim.setText("Soy Isim");
        jPanel1.add(soyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 30));
        soyisim.getAccessibleContext().setAccessibleName("soyisim");

        soyIsimTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyIsimTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(soyIsimTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 220, 30));

        tc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tc.setForeground(new java.awt.Color(240, 240, 240));
        tc.setText("TC");
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 30));
        tc.getAccessibleContext().setAccessibleName("tc");

        tcTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(tcTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        sifreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(sifreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 260, 30));

        label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(204, 255, 204));
        label2.setName("maas"); // NOI18N
        label2.setText("Maas");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenuActionPerformed
        GuiMuzeYoneticisi gmy=new GuiMuzeYoneticisi();
        this.setVisible(false);
        gmy.setVisible(true);
    }//GEN-LAST:event_anamenuActionPerformed

    private void maasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maasTextFieldActionPerformed

    private void isimTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isimTextField1ActionPerformed

    private void soyIsimTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyIsimTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyIsimTextField2ActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        isimT=isimTextField1.getText();
        soyisimT=soyIsimTextField2.getText();
        tcT=tcTextField1.getText();
        sifreT=sifreTextField.getText();
        maasT=maasTextField.getText();
        if(isimT.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Isim boş bırakılamaz.");
            sifirla();
        }
        else if(soyisimT.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Soyisim boş bırakılamaz.");
            sifirla();
        }
        else if(tcT.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tc numarası boş bırakılamaz.");
            sifirla();
        }
        else if(!isNumeric(tcT))
        {
            JOptionPane.showMessageDialog(null, "TC numarası sadece rakamlardan oluşa bilir.");
            sifirla();
        }
        else if(tcT.length()!=11)
        {
           JOptionPane.showMessageDialog(null, "TC numarası 11 rakamdan oluşmalıdır."); 
           sifirla();
        }
        else if(!isNumeric(maasT))
        {
           JOptionPane.showMessageDialog(null, "Maaş sadece rakamlardan oluşa bilir.");         
           sifirla();
        }
        else if(Integer.valueOf(maasT)<=0)
        {
            JOptionPane.showMessageDialog(null, "Maaş değeri sıfırdan düşük olamaz.");
            sifirla();
        }
        else
        {
            try {
                if(ConnectionDB.isciEkle(isimT, soyisimT, sifreT, maasT, tcT))
                {
                    JOptionPane.showMessageDialog(null, "Personel eklendi.");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Eklenemedi.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(GuiPersonelEkle.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
    }//GEN-LAST:event_ekleActionPerformed

    private void tcTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcTextField1ActionPerformed

    private void sifreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreTextFieldActionPerformed

    
    public boolean isNumeric(String s) {  
        return s != null && s.matches("[-+]?\\d*\\.?\\d+");  
    }
    public void sifirla()
    {
        tcTextField1.setText("");
        isimTextField1.setText("");
        soyIsimTextField2.setText("");
        maasTextField.setText("");
        sifreTextField.setText("");
        maasTextField.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPersonelEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button anamenu;
    private java.awt.Button ekle;
    private java.awt.Label isim;
    private javax.swing.JTextField isimTextField1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private javax.swing.JTextField maasTextField;
    private java.awt.Label sifre;
    private javax.swing.JTextField sifreTextField;
    private javax.swing.JTextField soyIsimTextField2;
    private java.awt.Label soyisim;
    private java.awt.Label tc;
    private javax.swing.JTextField tcTextField1;
    // End of variables declaration//GEN-END:variables
}
