/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Huseyn
 */
public class GuiStartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public GuiStartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kayitOl = new java.awt.Button();
        oturumAc = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muzelogo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 420, 460));

        kayitOl.setActionCommand("kayıtOl");
        kayitOl.setBackground(new java.awt.Color(0, 0, 0));
        kayitOl.setForeground(new java.awt.Color(240, 240, 240));
        kayitOl.setLabel("KAYIT OL");
        kayitOl.setName("kayıtOl"); // NOI18N
        kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitOlActionPerformed(evt);
            }
        });
        jPanel1.add(kayitOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));
        kayitOl.getAccessibleContext().setAccessibleName("kayıtOl");

        oturumAc.setActionCommand("oturumAc");
        oturumAc.setBackground(new java.awt.Color(0, 0, 0));
        oturumAc.setForeground(new java.awt.Color(240, 240, 240));
        oturumAc.setLabel("OTURUM AÇ");
        oturumAc.setName("oturumAc"); // NOI18N
        oturumAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oturumAcActionPerformed(evt);
            }
        });
        jPanel1.add(oturumAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 170, 40));
        oturumAc.getAccessibleContext().setAccessibleName("oturumAc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitOlActionPerformed
        GuiSignUp g= new GuiSignUp();
        this.setVisible(false);
        g.setVisible(true);
    }//GEN-LAST:event_kayitOlActionPerformed

    private void oturumAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oturumAcActionPerformed
        GuiLogin login=new GuiLogin();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_oturumAcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiStartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConnectionDB db = new ConnectionDB();
                try {
                    db.qosul();
                    //db.oturumAc();
                } catch (SQLException ex) {
                    Logger.getLogger(GuiStartPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                 new GuiStartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button kayitOl;
    private java.awt.Button oturumAc;
    // End of variables declaration//GEN-END:variables
}
