/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muze;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gruhayn
 */
public class KrediKarti extends javax.swing.JFrame {

    /**
     * Creates new form KrediKarti
     */
    public KrediKarti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kartNumarasitextField = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        aytextField = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        yiltextField = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        soyisimTextField = new javax.swing.JTextField();
        isimTextField = new javax.swing.JTextField();
        CCVTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tutar_kelime_Label = new javax.swing.JLabel();
        tutarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logomini.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 110));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kart Numarası:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        kartNumarasitextField.setBackground(new java.awt.Color(0, 0, 0));
        kartNumarasitextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kartNumarasitextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        kartNumarasitextField.setForeground(new java.awt.Color(255, 255, 255));
        kartNumarasitextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartNumarasitextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(kartNumarasitextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ay:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 30, 40));

        aytextField.setBackground(new java.awt.Color(0, 0, 0));
        aytextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        aytextField.setForeground(new java.awt.Color(255, 255, 255));
        aytextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aytextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(aytextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 40, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Yıl:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 40, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Isim:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 40));

        label1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Soyisim:");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        yiltextField.setBackground(new java.awt.Color(0, 0, 0));
        yiltextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        yiltextField.setForeground(new java.awt.Color(255, 255, 255));
        yiltextField.setPreferredSize(new java.awt.Dimension(8, 21));
        yiltextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yiltextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(yiltextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CCV:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 50, 40));

        soyisimTextField.setBackground(new java.awt.Color(0, 0, 0));
        soyisimTextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        soyisimTextField.setForeground(new java.awt.Color(255, 255, 255));
        soyisimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyisimTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(soyisimTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 240, 30));

        isimTextField.setBackground(new java.awt.Color(0, 0, 0));
        isimTextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        isimTextField.setForeground(new java.awt.Color(255, 255, 255));
        isimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(isimTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 30));

        CCVTextField.setBackground(new java.awt.Color(0, 0, 0));
        CCVTextField.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        CCVTextField.setForeground(new java.awt.Color(255, 255, 255));
        CCVTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCVTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(CCVTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 80, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("Kart bilgilerinizi doğrulayınız.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 370, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Öde");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, 30));

        tutar_kelime_Label.setBackground(new java.awt.Color(0, 0, 0));
        tutar_kelime_Label.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tutar_kelime_Label.setForeground(new java.awt.Color(255, 255, 255));
        tutar_kelime_Label.setText("Tutar:");
        jPanel1.add(tutar_kelime_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, 30));

        tutarLabel.setBackground(new java.awt.Color(0, 0, 0));
        tutarLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tutarLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tutarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kartNumarasitextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartNumarasitextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kartNumarasitextFieldActionPerformed

    private void aytextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aytextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aytextFieldActionPerformed

    private void yiltextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yiltextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yiltextFieldActionPerformed

    private void soyisimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyisimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyisimTextFieldActionPerformed

    private void isimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isimTextFieldActionPerformed

    private void CCVTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCVTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCVTextFieldActionPerformed

    public void setTutarLabel(String text) {
        tutarLabel.setText(text);
    }

    public JLabel getTutar_kelime_Label() {
        return tutar_kelime_Label;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String isim,soyisim,kartNumarasi,ay,yil,CCV;
        isim=isimTextField.getText();
        soyisim=soyisimTextField.getText();
        kartNumarasi=kartNumarasitextField.getText();
        ay=aytextField.getText();
        yil=yiltextField.getText();
        CCV=CCVTextField.getText();
        if(isim.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Isim boş bırakılamaz.");
            sifirla();
        }
        else if(soyisim.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Soyisim boş bırakılamaz.");
            sifirla();
        }
        else if(kartNumarasi.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Kart numarasi boş bırakılamaz.");            
            sifirla();
        }
        else if(!isNumeric(kartNumarasi))
        {
            JOptionPane.showMessageDialog(null, "Kart numarasi sadece rakamlardan olusmalidir.");
            sifirla();
        }
        else if(kartNumarasi.length()!=16)
        {
            JOptionPane.showMessageDialog(null, "Kart numarasi 16 rakamdan olusmalidir.");
            sifirla();
        }
        else if (ay.equals("") || (0>=Integer.valueOf(ay) || Integer.valueOf(ay)>12)){
            JOptionPane.showMessageDialog(null, "Ay boş bırakılamaz ve 1-12 rakamları arasında olmalıdır.");
            sifirla();
        }
        else if(yil.equals("") || Integer.valueOf(yil)<2018)
        {
            JOptionPane.showMessageDialog(null, "Yıl boş bırakılamaz ve 2018'den büyük eşit olmalıdır.");
            sifirla();
        }
        else if(Integer.valueOf(yil)==2018 && Integer.valueOf(ay)<=5){
            JOptionPane.showMessageDialog(null, "Kartınızın kullanım tarihi bitmişdir.");
            sifirla();
        }
        else if(CCV.equals("") && !isNumeric(CCV))
        {
            JOptionPane.showMessageDialog(null, "CCV boş bırakılamaz ve sadece rakamlardan oluşmalıdır.");
            sifirla();
        }
        else if(CCV.length()!=3 && CCV.length()!=4)
        {
            JOptionPane.showMessageDialog(null, "CCV değeri doğru değildir.");
            sifirla();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Kart bilgileriniz onaylandı.Biletiniz alındı.");
            GuiMusteri gm=new GuiMusteri();
            this.setVisible(false);
            gm.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void sifirla()
    {
        isimTextField.setText("");
        soyisimTextField.setText("");
        kartNumarasitextField.setText("");
        aytextField.setText("");
        yiltextField.setText("");
        CCVTextField.setText("");
    }
    
    public boolean isNumeric(String s) {  
        return s != null && s.matches("[-+]?\\d*\\.?\\d+");  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediKarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediKarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediKarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediKarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrediKarti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCVTextField;
    private java.awt.TextField aytextField;
    private javax.swing.JTextField isimTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField kartNumarasitextField;
    private java.awt.Label label1;
    private javax.swing.JTextField soyisimTextField;
    private javax.swing.JLabel tutarLabel;
    private javax.swing.JLabel tutar_kelime_Label;
    private java.awt.TextField yiltextField;
    // End of variables declaration//GEN-END:variables
}
